create or replace TABLE DEV_EDP.EDP_DATA.AUDIT_CUSTOMER_ATTRIBUTE (
	AUDIT_TYPE_DESC VARCHAR(100) NOT NULL,
	CUSTOMER_ID NUMBER(38,0) NOT NULL,
	ATTRIBUTE_ID NUMBER(38,0) NOT NULL,
	ATTRIBUTE_VALUE VARCHAR(16777216),
	ENGINE_NAME VARCHAR(100),
	INSERT_DTM TIMESTAMP_NTZ(9),
	UPDATE_DTM TIMESTAMP_NTZ(9),
	SNAPSHOT_DTM TIMESTAMP_NTZ(9) NOT NULL DEFAULT CAST(CONVERT_TIMEZONE('UTC', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ(9))) AS TIMESTAMP_NTZ(9))
);