create or replace TABLE DEV_EDP.EDP_DATA.DIM_COUPON (
	COUPON_ID NUMBER(38,0) NOT NULL autoincrement COMMENT 'A unique promotion identifier',
	COUPON_DESC VARCHAR(50) COMMENT 'Name of a sales promotion or coupon, such as :\n- DISCOUNTS W/O ASSIGNED CODE\n- LOW PRICE GUARANTEE VS. COMPETITOR\n- LOW PRICE GUARANTEE VS. CW RETAIL\n- DISC RETN-BOUGHT AT RET STORE-NO RECEIPT\n- RAIN CHECK',
	COUPON_CODE VARCHAR(30) COMMENT 'A code for a sales promotion\nCoupon Code\tCoupon Name\n0\tDISCOUNTS W/O ASSIGNED CODE\n1100\t$10 OFF PCH--21 MASTER PEEL-OFF--GS, GEO\n1103\t$10 OFF PCH--21 MASTER PEEL-OFF--GS CMB/RT 0-\n1104\t$10 OFF PCH--21 MASTER PEEL-OFF--GS DIRECT 0-\n1105\t$10 OFF PCH--21 MASTER PEEL-OFF--GS CMB/RT 13\n1106\t$10 OFF PCH--21 MASTER PEEL-OFF--GS CMB/RT 19\n1107\t$10 OFF PCH--21 MASTER PEEL-OFF--NGS BYR & PR\n1109\t$10 OFF PCH--21 MASTER PC--GS CMB/RT 0-12\n1110\t$10 OFF PCH--21 MASTER PC--GS DIRECT 0-18\n1111\tGOOD SAM MEMBER DISCOUNT\n1112\tXTRA 5% OFF INSTALLATION--GS ELITE MEMBERS\n1113\t$29 INSTALL--GSC BENEFIT\n1114\t$10 OFF PCH--21 MASTER PC--GS CMB/RT 13-18\n1115\t$39 INSTALL--GSC BENEFIT\n1116\t$149 INSTALL--GSC BENEFIT\n1117\t$59 INSTALL--GSC BENEFIT\n1118\t$79 INSTALL--GSC BENEFIT\n1119\t$10 OFF PCH--21 MASTER PC--GS CMB/RT 19-24\n1120\t$10 OFF PCH--21 MASTER PC--NGS BYR & PROSP\n',
	CAMPAIGN_START_DATE DATE COMMENT 'Promotion begin date',
	CAMPAIGN_END_DATE DATE COMMENT 'Promotion end date',
	RECORD_LOAD_DTM DATE COMMENT 'Record load datetime',
	CAMPAIGN_TYPE_CODE NUMBER(38,0) COMMENT 'A code identifying a promotion group, such as:\n- 235\n- 234\n- 232\n- 210',
	COUPON_CHANNEL_DESC VARCHAR(250) COMMENT 'Description of coupon channel, such as: RETAIL, CC/RETAIL\n ',
	COUPON_LEVEL_TYPE_DESC VARCHAR(10) COMMENT 'A code for transaction level types, such as \n- line\n- Order',
	CAMPAIGN_CODE VARCHAR(4) COMMENT 'A code for a campaign, such as \n002 \n050 \n040 \n017 \n020 ',
	CAMPAIGN_DESC VARCHAR(50) COMMENT 'Description of a campaign, such as:\nDISCOUNT MENU DROP-DOWN LIST            \n10 MAY CATALOG                          \n10 FEBRUARY RVVIEW                      \n10 SUMMER CATALOG                       \n10 EARLY SPRING CATALOG                 \n11 FALL CATALOG                         ',
	COUPON_STATUS_DESC VARCHAR(10) COMMENT 'Description of promotion status, such as \nVERIFIED',
	MEMBERSHIP_REQUIRED_IND VARCHAR(3) COMMENT 'A flag that indicates a membership coupon',
	COUPON_START_DATE DATE COMMENT 'Coupon start date',
	COUPON_END_DATE DATE COMMENT 'Coupon end date',
	APPLICATION_METHOD_DESC VARCHAR(20) COMMENT 'Description of how a coupon is applied to a transaction, such as Amount, percent',
	COUPON_REQUIRED_IND VARCHAR(5) COMMENT 'An indicator for ''is coupon required''',
	COUPON_DISCOUNT_VALUE NUMBER(38,0) COMMENT 'Amount of discount applied or percentage discounted',
	MINIMUM_ITEM_AMT VARCHAR(20) COMMENT 'Minimum item amount',
	MINIMUM_ORDER_AMT NUMBER(38,0) COMMENT 'Minimum order amount',
	constraint XPKCPNDIM primary key (COUPON_ID)
)COMMENT='A Coupon is the discount applied to a sale, this include the goodsam membership\nCoupon Code\tCoupon Name\n0\tDISCOUNTS W/O ASSIGNED CODE\n1100\t$10 OFF PCH--21 MASTER PEEL-OFF--GS, GEO\n1103\t$10 OFF PCH--21 MASTER PEEL-OFF--GS CMB/RT 0-\n1104\t$10 OFF PCH--21 MASTER PEEL-OFF--GS DIRECT 0-\n1105\t$10 OFF PCH--21 MASTER PEEL-OFF--GS CMB/RT 13\n1106\t$10 OFF PCH--21 MASTER PEEL-OFF--GS CMB/RT 19\n1107\t$10 OFF PCH--21 MASTER PEEL-OFF--NGS BYR & PR\n1109\t$10 OFF PCH--21 MASTER PC--GS CMB/RT 0-12\n1110\t$10 OFF PCH--21 MASTER PC--GS DIRECT 0-18\n1111\tGOOD SAM MEMBER DISCOUNT\n1112\tXTRA 5% OFF INSTALLATION--GS ELITE MEMBERS\n1113\t$29 INSTALL--GSC BENEFIT\n1114\t$10 OFF PCH--21 MASTER PC--GS CMB/RT 13-18\n1115\t$39 INSTALL--GSC BENEFIT\n1116\t$149 INSTALL--GSC BENEFIT\n1117\t$59 INSTALL--GSC BENEFIT\n1118\t$79 INSTALL--GSC BENEFIT\n1119\t$10 OFF PCH--21 MASTER PC--GS CMB/RT 19-24\n1120\t$10 OFF PCH--21 MASTER PC--NGS BYR & PROSP\n'
;