create or replace view DEV_STG.CUSTOMER_360.VW_ATTRIBUTE_TO_ZIP_MAP(
	CUSTOMER_ID,
	ATTRIBUTE_ID,
	ATTRIBUTE_VALUE
) as
WITH A AS 
(
Select ATTRIBUTE_VALUE,CUSTOMER_ID from DEV_EDP.EDP_DATA.FACT_CUSTOMER_ATTRIBUTE where ATTRIBUTE_ID = 22
)
SELECT FACT.CUSTOMER_ID, META.ATTRIBUTE_ID,
CASE WHEN FACT.ATTRIBUTE_VALUE IS NOT NULL THEN 'Y' END AS ATTRIBUTE_VALUE
FROM A FACT
LEFT JOIN
DEV_RAW.CUSTOMER_360.ATTRIBUTE_TO_ZIP_MAP GEO
ON GEO.ZIP_CODE = FACT.ATTRIBUTE_VALUE
LEFT JOIN DEV_INBOUND.CUSTOMER_360.META_CUSTOMER_ATTRIBUTE META
ON LOWER(GEO.ATTRIBUTE_NAME) = LOWER(META.ATTRIBUTE_NAME)
WHERE GEO.ATTRIBUTE_NAME IS NOT NULL;