create or replace view DEV_STG.CUSTOMER_360.VW_SEGMENT_UNPIVOT(
	CUSTOMER_ID,
	ATTRIBUTE_ID,
	ATTRIBUTE_VALUE
) as select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_high_intent_shopper_cw')) attribute_id , cast(customer_360_high_intent_shopper_cw as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_high_intent_shopper_cw is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_high_intent_shopper_ovt')) attribute_id , cast(customer_360_high_intent_shopper_ovt as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_high_intent_shopper_ovt is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_a_active')) attribute_id , cast(customer_360_rv_shopper_a_active as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_a_active is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_a_dormant')) attribute_id , cast(customer_360_rv_shopper_a_dormant as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_a_dormant is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_a_passive')) attribute_id , cast(customer_360_rv_shopper_a_passive as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_a_passive is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_ad_active')) attribute_id , cast(customer_360_rv_shopper_ad_active as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_ad_active is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_ad_dormant')) attribute_id , cast(customer_360_rv_shopper_ad_dormant as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_ad_dormant is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_ad_passive')) attribute_id , cast(customer_360_rv_shopper_ad_passive as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_ad_passive is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_b_active')) attribute_id , cast(customer_360_rv_shopper_b_active as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_b_active is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_b_dormant')) attribute_id , cast(customer_360_rv_shopper_b_dormant as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_b_dormant is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_b_passive')) attribute_id , cast(customer_360_rv_shopper_b_passive as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_b_passive is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_btr_active')) attribute_id , cast(customer_360_rv_shopper_btr_active as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_btr_active is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_btr_dormant')) attribute_id , cast(customer_360_rv_shopper_btr_dormant as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_btr_dormant is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_btr_passive')) attribute_id , cast(customer_360_rv_shopper_btr_passive as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_btr_passive is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_c_active')) attribute_id , cast(customer_360_rv_shopper_c_active as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_c_active is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_c_dormant')) attribute_id , cast(customer_360_rv_shopper_c_dormant as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_c_dormant is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_c_passive')) attribute_id , cast(customer_360_rv_shopper_c_passive as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_c_passive is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_ct_dormant')) attribute_id , cast(customer_360_rv_shopper_ct_dormant as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_ct_dormant is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_fd_active')) attribute_id , cast(customer_360_rv_shopper_fd_active as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_fd_active is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_fd_dormant')) attribute_id , cast(customer_360_rv_shopper_fd_dormant as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_fd_dormant is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_fd_passive')) attribute_id , cast(customer_360_rv_shopper_fd_passive as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_fd_passive is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_fth_active')) attribute_id , cast(customer_360_rv_shopper_fth_active as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_fth_active is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_fth_dormant')) attribute_id , cast(customer_360_rv_shopper_fth_dormant as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_fth_dormant is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_fth_passive')) attribute_id , cast(customer_360_rv_shopper_fth_passive as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_fth_passive is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_fw_active')) attribute_id , cast(customer_360_rv_shopper_fw_active as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_fw_active is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_fw_dormant')) attribute_id , cast(customer_360_rv_shopper_fw_dormant as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_fw_dormant is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_fw_passive')) attribute_id , cast(customer_360_rv_shopper_fw_passive as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_fw_passive is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_htt_active')) attribute_id , cast(customer_360_rv_shopper_htt_active as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_htt_active is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_htt_dormant')) attribute_id , cast(customer_360_rv_shopper_htt_dormant as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_htt_dormant is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_htt_passive')) attribute_id , cast(customer_360_rv_shopper_htt_passive as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_htt_passive is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_new_active')) attribute_id , cast(customer_360_rv_shopper_new_active as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_new_active is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_new_dormant')) attribute_id , cast(customer_360_rv_shopper_new_dormant as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_new_dormant is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_new_passive')) attribute_id , cast(customer_360_rv_shopper_new_passive as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_new_passive is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_ps_active')) attribute_id , cast(customer_360_rv_shopper_ps_active as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_ps_active is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_ps_dormant')) attribute_id , cast(customer_360_rv_shopper_ps_dormant as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_ps_dormant is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_ps_passive')) attribute_id , cast(customer_360_rv_shopper_ps_passive as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_ps_passive is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_tc_active')) attribute_id , cast(customer_360_rv_shopper_tc_active as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_tc_active is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_tc_dormant')) attribute_id , cast(customer_360_rv_shopper_tc_dormant as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_tc_dormant is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_tc_passive')) attribute_id , cast(customer_360_rv_shopper_tc_passive as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_tc_passive is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_tt_active')) attribute_id , cast(customer_360_rv_shopper_tt_active as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_tt_active is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_tt_dormant')) attribute_id , cast(customer_360_rv_shopper_tt_dormant as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_tt_dormant is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_tt_passive')) attribute_id , cast(customer_360_rv_shopper_tt_passive as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_tt_passive is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_tth_active')) attribute_id , cast(customer_360_rv_shopper_tth_active as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_tth_active is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_tth_dormant')) attribute_id , cast(customer_360_rv_shopper_tth_dormant as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_tth_dormant is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_tth_passive')) attribute_id , cast(customer_360_rv_shopper_tth_passive as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_tth_passive is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_used_active')) attribute_id , cast(customer_360_rv_shopper_used_active as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_used_active is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_used_dormant')) attribute_id , cast(customer_360_rv_shopper_used_dormant as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_used_dormant is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table 
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(SOURCE_COLUMN_NAME) = lower('customer_360_rv_shopper_used_passive')) attribute_id , cast(customer_360_rv_shopper_used_passive as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where customer_360_rv_shopper_used_passive is not null;