create or replace view DEV_STG.CUSTOMER_360.VW_SEGMENT_UNPIVOT_TRANSFORM(
	CUSTOMER_ID,
	ATTRIBUTE_ID,
	ATTRIBUTE_VALUE
) as select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(source_column_name) = lower('high_intent_shopper_cw')) attribute_id , cast(IFF (lower(customer_360_high_intent_shopper_cw)='true' ,'Y' ,null) as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where attribute_value is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(source_column_name) = lower('high_intent_shopper_ovt')) attribute_id , cast(IFF (lower(customer_360_high_intent_shopper_ovt)='true' ,'Y' ,null) as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where attribute_value is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(source_column_name) = lower('rv_shopper_a')) attribute_id , cast(IFF (lower(customer_360_rv_shopper_a_active)='true' ,'ACTIVE' ,IFF (lower(customer_360_rv_shopper_a_passive)='true','PASSIVE',IFF (lower(customer_360_rv_shopper_a_dormant)='true','DORMANT',null))) as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where attribute_value is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(source_column_name) = lower('rv_shopper_ad')) attribute_id , cast(IFF (lower(customer_360_rv_shopper_ad_active)='true' ,'ACTIVE' ,IFF (lower(customer_360_rv_shopper_ad_passive)='true','PASSIVE',IFF (lower(customer_360_rv_shopper_ad_dormant)='true','DORMANT',null))) as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where attribute_value is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(source_column_name) = lower('rv_shopper_b')) attribute_id , cast(IFF (lower(customer_360_rv_shopper_b_active)='true' ,'ACTIVE' ,IFF (lower(customer_360_rv_shopper_b_passive)='true','PASSIVE',IFF (lower(customer_360_rv_shopper_b_dormant)='true','DORMANT',null))) as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where attribute_value is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(source_column_name) = lower('rv_shopper_btr')) attribute_id , cast(IFF (lower(customer_360_rv_shopper_btr_active)='true' ,'ACTIVE' ,IFF (lower(customer_360_rv_shopper_btr_passive)='true','PASSIVE',IFF (lower(customer_360_rv_shopper_btr_dormant)='true','DORMANT',null))) as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where attribute_value is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(source_column_name) = lower('rv_shopper_c')) attribute_id , cast(IFF (lower(customer_360_rv_shopper_c_active)='true' ,'ACTIVE' ,IFF (lower(customer_360_rv_shopper_c_passive)='true','PASSIVE',IFF (lower(customer_360_rv_shopper_c_dormant)='true','DORMANT',null))) as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where attribute_value is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(source_column_name) = lower('rv_shopper_fd')) attribute_id , cast(IFF (lower(customer_360_rv_shopper_fd_active)='true' ,'ACTIVE' ,IFF (lower(customer_360_rv_shopper_fd_passive)='true','PASSIVE',IFF (lower(customer_360_rv_shopper_fd_dormant)='true','DORMANT',null))) as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where attribute_value is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(source_column_name) = lower('rv_shopper_fth')) attribute_id , cast(IFF (lower(customer_360_rv_shopper_fth_active)='true' ,'ACTIVE' ,IFF (lower(customer_360_rv_shopper_fth_passive)='true','PASSIVE',IFF (lower(customer_360_rv_shopper_fth_dormant)='true','DORMANT',null))) as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where attribute_value is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(source_column_name) = lower('rv_shopper_fw')) attribute_id , cast(IFF (lower(customer_360_rv_shopper_fw_active)='true' ,'ACTIVE' ,IFF (lower(customer_360_rv_shopper_fw_passive)='true','PASSIVE',IFF (lower(customer_360_rv_shopper_fw_dormant)='true','DORMANT',null))) as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where attribute_value is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(source_column_name) = lower('rv_shopper_htt')) attribute_id , cast(IFF (lower(customer_360_rv_shopper_htt_active)='true' ,'ACTIVE' ,IFF (lower(customer_360_rv_shopper_htt_passive)='true','PASSIVE',IFF (lower(customer_360_rv_shopper_htt_dormant)='true','DORMANT',null))) as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where attribute_value is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(source_column_name) = lower('rv_shopper_new')) attribute_id , cast(IFF (lower(customer_360_rv_shopper_new_active)='true' ,'ACTIVE' ,IFF (lower(customer_360_rv_shopper_new_passive)='true','PASSIVE',IFF (lower(customer_360_rv_shopper_new_dormant)='true','DORMANT',null))) as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where attribute_value is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(source_column_name) = lower('rv_shopper_ps')) attribute_id , cast(IFF (lower(customer_360_rv_shopper_ps_active)='true' ,'ACTIVE' ,IFF (lower(customer_360_rv_shopper_ps_passive)='true','PASSIVE',IFF (lower(customer_360_rv_shopper_ps_dormant)='true','DORMANT',null))) as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where attribute_value is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(source_column_name) = lower('rv_shopper_tc')) attribute_id , cast(IFF (lower(customer_360_rv_shopper_tc_active)='true' ,'ACTIVE' ,IFF (lower(customer_360_rv_shopper_tc_passive)='true','PASSIVE',IFF (lower(customer_360_rv_shopper_tc_dormant)='true','DORMANT',null))) as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where attribute_value is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(source_column_name) = lower('rv_shopper_tt')) attribute_id , cast(IFF (lower(customer_360_rv_shopper_tt_active)='true' ,'ACTIVE' ,IFF (lower(customer_360_rv_shopper_tt_passive)='true','PASSIVE',IFF (lower(customer_360_rv_shopper_tt_dormant)='true','DORMANT',null))) as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where attribute_value is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(source_column_name) = lower('rv_shopper_tth')) attribute_id , cast(IFF (lower(customer_360_rv_shopper_tth_active)='true' ,'ACTIVE' ,IFF (lower(customer_360_rv_shopper_tth_passive)='true','PASSIVE',IFF (lower(customer_360_rv_shopper_tth_dormant)='true','DORMANT',null))) as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where attribute_value is not null
 union all select cstmr_id as customer_id, (select attribute_id from dev_inbound.customer_360.meta_customer_attribute inner join dev_inbound.customer_360.meta_customer_table
on fk_table_id=table_id where table_name='VW_SEGMENT' and lower(source_column_name) = lower('rv_shopper_used')) attribute_id , cast(IFF (lower(customer_360_rv_shopper_used_active)='true' ,'ACTIVE' ,IFF (lower(customer_360_rv_shopper_used_passive)='true','PASSIVE',IFF (lower(customer_360_rv_shopper_used_dormant)='true','DORMANT',null))) as varchar) attribute_value  from DEV_INBOUND.CUSTOMER_360.VW_SEGMENT where attribute_value is not null;