create or replace TABLE DEV_EDP.EDP_DATA.DIM_TRANSACTION_TYPE (
	TRANSACTION_TYPE_ID NUMBER(38,0) NOT NULL autoincrement COMMENT 'A unique transaction type identifier',
	TRANSACTION_TYPE_DESC VARCHAR(60) COMMENT 'Description of a transaction type, such as TRANSACTION_TYPE\n190 Monticello\n191 Tulsa\n920 Overtons Greenville\n930 Overtons Raleigh\n601 Gander Bowling Green\n602 Gander Ocala\n603 Gander Newnan\n604 Gander Cedar Rapids\n605 Gander Ft Pierce\n642 Gander Portage\n647 Gander Tonawanda\n615 Gander Florence\n655 Gander Baraboo\n626 Gander York\n',
	TRANSACTION_TYPE_CODE VARCHAR(60) COMMENT 'A code identifying a type of transaction, such as \nTRANSACTION_TYPE\n190 Monticello\n191 Tulsa\n920 Overtons Greenville\n930 Overtons Raleigh\n601 Gander Bowling Green\n602 Gander Ocala\n603 Gander Newnan\n604 Gander Cedar Rapids\n605 Gander Ft Pierce\n642 Gander Portage\n647 Gander Tonawanda\n615 Gander Florence\n655 Gander Baraboo\n626 Gander York\n',
	RECORD_LOAD_DTM DATE COMMENT 'Record load datetime',
	CATEGORY_DESC VARCHAR(15) COMMENT 'Descriptiom of an order line type group such as Mixed, return, order',
	TRANSACTION_TYPE_LEVEL_DESC VARCHAR(15) COMMENT 'Description of a transaction type level such as order, line',
	constraint XPKTRNSTYPEDIM primary key (TRANSACTION_TYPE_ID)
)COMMENT='Type of transaction, such as sales, refund etc\nTransaction Type                          Category  Transaction type level\n400 GANDER AMAZON FBA\t        MIXED\tORDER\n425 CONSIGNMENT LOCATION      MIXED\tORDER\nPICK, PACK, SHIP LINE\t       ORDER\tLINE\nBILL ONLY W INV DECREMENT       LINE\tORDER\tLINE\nSPECIAL ORDER LINE\t     ORDER\tLINE\nBILL ONLY LINE\t                   ORDER\tLINE\nSHIP ONLY LINE\t                  ORDER\tLINE\nRETURN LINE\t                 RETURN\tLINE\nCREDIT ONLY LINE\t                 RETURN\tLINE\nSTANDARD LINE\t                  ORDER\tLINE\n'
;