create or replace TABLE DEV_EDP.EDP_DATA.DIM_CUSTOMER_ATTRIBUTE (
	ATTRIBUTE_ID NUMBER(38,0),
	ATTRIBUTE_NAME VARCHAR(100),
	DISPLAY_NAME VARCHAR(100),
	ATTRIBUTE_DESC VARCHAR(200),
	ATTRIBUTE_CATEGORY_DESC VARCHAR(80),
	ATTRIBUTE_SUBCATEGORY_DESC VARCHAR(50),
	ENGINE_NAME VARCHAR(40),
	DEFAULT_VALUE VARCHAR(200),
	IS_TARGET_ATTRIBUTE VARCHAR(1)
);