create or replace TABLE DEV_EDP.EDP_DATA.FACT_CUSTOMER_ATTRIBUTE (
	CUSTOMER_ID NUMBER(38,0) NOT NULL,
	ATTRIBUTE_ID NUMBER(38,0) NOT NULL,
	ATTRIBUTE_VALUE VARCHAR(16777216),
	ENGINE_NAME VARCHAR(16777216),
	INSERT_DTM TIMESTAMP_NTZ(9),
	UPDATE_DTM TIMESTAMP_NTZ(9),
	constraint PK_FACT_CUSTOMER_ATTRIBUTE primary key (CUSTOMER_ID, ATTRIBUTE_ID)
);