create or replace TABLE DEV_RAW.EDW_CWH_EDW_DBO.MDM_CSTMR_EMAIL (
	CSTMR_ID NUMBER(38,0),
	MDM_EMAIL_ID VARCHAR(20),
	EMAIL_ID NUMBER(38,0) NOT NULL,
	DS_CD VARCHAR(20),
	EMAIL_ADDR VARCHAR(80),
	EMAIL_TYPE_DESC VARCHAR(20),
	EMAIL_USG_TYPE_DESC VARCHAR(20),
	LOAD_DTM TIMESTAMP_NTZ(3),
	"Is_Deleted" NUMBER(38,0),
	constraint PK_MDM_CSTMR_EMAIL_XPKCustomerEmail primary key (EMAIL_ID)
);