create or replace TABLE DEV_RAW.EDW_CWH_EDW_DBO.MDM_CSTMR_ALT (
	CSTMR_ID NUMBER(38,0),
	ALT_ID NUMBER(38,0) NOT NULL,
	ALT_ID_VALUE_NBR VARCHAR(50),
	ALT_ID_TYPE_CD VARCHAR(30),
	DS_CD VARCHAR(20),
	MDM_ALT_ID VARCHAR(20),
	LOAD_DTM TIMESTAMP_NTZ(3),
	"Is_Deleted" NUMBER(38,0),
	constraint PK_MDM_CSTMR_ALT_XPKCustomerAlternate primary key (ALT_ID)
);