create or replace TABLE DEV_STG.CUSTOMER_360.META_CUSTOMER_ATTRIBUTE (
	FK_TABLE_ID NUMBER(38,0),
	ATTRIBUTE_ID NUMBER(38,0),
	ATTRIBUTE_NAME VARCHAR(100),
	ATTRIBUTE_DESC VARCHAR(200),
	ATTRIBUTE_CATEGORY_DESC VARCHAR(80),
	DEFAULT_VALUE VARCHAR(200),
	VALUE_DATATYPE VARCHAR(20),
	ATTRIBUTE_SUBCATEGORY_DESC VARCHAR(50),
	RECORD_CREATE_DATE DATE,
	RECORD_UPDATE_DATE DATE,
	DISPLAY_NAME VARCHAR(100),
	IS_TARGET_ATTRIBUTE VARCHAR(1),
	ENGINE_NAME VARCHAR(40),
	IS_TRANSFORM_ATTRIBUTE VARCHAR(1),
	TRANSFORMATION_RULE VARCHAR(16777216),
	SOURCE_COLUMN_NAME VARCHAR(100)
);