create or replace TABLE DEV_STG.CUSTOMER_360.META_CUSTOMER_TABLE (
	TABLE_ID NUMBER(38,0),
	DATABASE_NAME VARCHAR(100),
	SCHEMA_NAME VARCHAR(100),
	TABLE_NAME VARCHAR(100),
	TABLE_DESC VARCHAR(255),
	TABLE_CATEGORY_DESC VARCHAR(255),
	ENGINE_NAME VARCHAR(100)
);