create or replace task DEV_STG.CUSTOMER_360.CUST360_LOGGING
	warehouse=CW_DEV_ETL_S_CS_WH
	after DEV_STG.CUSTOMER_360.CUST360_DAILY_RUN
	as INSERT INTO SANDBOX_DB.ANIKET.CUST360_TASK_LOGGING VALUES (CURRENT_TIMESTAMP, "CUST360_DAILY_RUN - COMPLETED SUCCESFULLY");