create or replace task DEV_STG.CUSTOMER_360.SEGMENT_DATA_REFRESH
	warehouse=CW_DEV_ETL_S_CS_WH
	after DEV_STG.CUSTOMER_360.MDM_EMAIL_DATA_REFRESH
	as CREATE OR REPLACE TABLE DEV_RAW.SEGMENT_PERSONAS.USERS CLONE DEV_INBOUND_SEGMENT.PERSONAS_PERSONAS_PROD.USERS;