create or replace view DEV_EDP.EDP.VW_DIM_CUSTOMER360(
	"Customer ID",
	"Cold Weather - North",
	"Lakes & Coastal",
	"Warm Weather - South",
	"Address Line 1",
	"Address Line 2",
	"Age",
	"City Name",
	"Country",
	"County Name",
	"Customer Ind",
	"Customer Type Desc",
	"Email Business",
	"Email Personal",
	"First Name",
	"Full Name",
	"Gender",
	"Has Email Business",
	"Has Email Personal",
	"Has Phone Business",
	"Has Phone Personal",
	"Last Name",
	"Latitude",
	"Longitude",
	"MDM Customer ID",
	"Middle Name",
	"Phone Business",
	"Phone Personal",
	"Zip",
	"Zip Extension",
	"Prefix",
	"RV Type",
	"State",
	"Suffix",
	"Title",
	"High Intent Shopper CW",
	"High Intent Shopper Overton's",
	"RV Shopper A",
	"RV Shopper AD",
	"RV Shopper B",
	"RV Shopper BTR",
	"RV Shopper C",
	"RV Shopper FD",
	"RV Shopper FTH",
	"RV Shopper FW",
	"RV Shopper HTT",
	"RV Shopper New",
	"RV Shopper PS",
	"RV Shopper TC",
	"RV Shopper TT",
	"RV Shopper TTH",
	"RV Shopper Used"
) as select * from dev_edp.edp_data.dim_customer360;